services:
    disweb.yandex.cli:
        build:
            context: .
            dockerfile: Dockerfile
        image: disweb.yandex.cli
        container_name: disweb.yandex.cli
        environment:
            YC_TOKEN: "${YC_TOKEN:-}"
            YC_CLOUD_ID: "${YC_CLOUD_ID:-}"
            YC_FOLDER_ID: "${YC_FOLDER_ID:-}"
            YC_COMPUTE_DEFAULT_ZONE: "${YC_COMPUTE_DEFAULT_ZONE:-ru-central1-b}"
            SSH_KEY: "${SSH_KEY:-}"
            INTERNAL_SG_ID: "${INTERNAL_SG_ID:-}"
            INTERNAL_SUBNET_ID: "${INTERNAL_SUBNET_ID:-}"
            EXTERNAL_SG_ID: "${EXTERNAL_SG_ID:-}"
            EXTERNAL_SUBNET_ID: "${EXTERNAL_SUBNET_ID:-}"
            EXTERNAL_IP_VAL: "${EXTERNAL_IP_VAL:-}"
            BASTION_NAME: "${BASTION_NAME:-otus-bastion-host}"
            BASTION_INTERNAL_IP: "${BASTION_INTERNAL_IP:-172.16.16.254}"
            BASTION_USER: "${BASTION_USER:-bastion}"
            INTERNAL_SERVER_1_NAME: "${INTERNAL_SERVER_1_NAME:-otus-test-vm-1}"
            INTERNAL_SERVER_1_USER: "${INTERNAL_SERVER_1_USER:-test}"
            INTERNAL_SERVER_2_NAME: "${INTERNAL_SERVER_2_NAME:-otus-test-vm-2}"
            INTERNAL_SERVER_2_USER: "${INTERNAL_SERVER_2_USER:-test}"
            IP_NAME: "${IP_NAME:-bastion-public-ip}"
            EXTERNAL_NETWORK_NAME: "${EXTERNAL_NETWORK_NAME:-external-bastion-network}"
            EXTERNAL_SUBNET_NAME: "${EXTERNAL_SUBNET_NAME:-bastion-external-segment}"
            EXTERNAL_CIDR: "${EXTERNAL_CIDR:-172.16.17.0/28}"
            INTERNAL_NETWORK_NAME: "${INTERNAL_NETWORK_NAME:-internal-bastion-network}"
            INTERNAL_SUBNET_NAME: "${INTERNAL_SUBNET_NAME:-bastion-internal-segment}"
            INTERNAL_CIDR: "${INTERNAL_CIDR:-172.16.16.0/24}"
            EXTERNAL_SG_NAME: "${EXTERNAL_SG_NAME:-secure-bastion-sg}"
            EXTERNAL_SG_INCOM_CIDR: "${EXTERNAL_SG_INCOM_CIDR:-0.0.0.0/0}"
            INTERNAL_SG_NAME: "${INTERNAL_SG_NAME:-internal-bastion-sg}"
            INTERNAL_SG_INCOM_CIDR: "${INTERNAL_SG_INCOM_CIDR:-172.16.16.254/32}"
            OPENING_PORT: "${OPENING_PORT:-22}"
